#!/bin/bash

# Create config folder if necessary
if [ ! -d "$HOME/.config/alacritty" ]
then
  mkdir -p "$HOME/.config/alacritty"
  echo "Creating alacritty config folder"
fi

# Creating symbolic link
echo "Creating symbolic link"
ln -sf "$PWD/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"
