#import = [
#    "~/.config/alacritty/themes/themes/tomorrow_night.toml"
#]

[env]
TERM = "xterm-256color"

[font.normal]
#family = "Hack Nerd Font Mono"
family = "Berkeley Mono"
style = "Regular"

[window]
decorations = "none"
opacity = 1
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5

#[colors.normal]
#blue = "#7aa6da"

#[general]
#live_config_reload = true

