#!/bin/bash
set -e
mkdir -p "$HOME/.config/alacritty"
echo "linking alacritty config"
ln -sf "$PWD/alacritty.toml" "$HOME/.config/alacritty/alacritty.toml"
ls -l "$HOME/.config/alacritty/alacritty.toml"

