#!/bin/bash

# From get.docker
is_wsl() {
	case "$(uname -r)" in
	*microsoft* ) true ;; # WSL 2
	*Microsoft* ) true ;; # WSL 1
	* ) false;;
	esac
}

# Only on linux workstation
if ! is_wsl; then
  echo "Setup alacritty"
  cd alacritty && ./setup
  cd .. 
fi

# Workstation and WSL 
for i in bash git vim tmux python;
do
  echo "Setup $i"
  cd $i && ./setup
  cd ..
done

