#!/bin/bash

# Updating repository and upgrading system 
echo -e "\n-- Update and upgrade" 
sudo apt update
sudo apt upgrade  -y

echo -e "\n-- Installing various app from debian package manager"
sudo apt install vim tmux entr tree xclip shellcheck ripgrep batcat -qq

# Install github CLI
echo -e "\n-- Installing gh"
if [ "$(which gh)" != "" ]; then
  "$PWD/install/install-gh"
fi

# install and config python
echo -e "\n-- Installing Python"
"$PWD/install/install-python"

# Install R
echo -e "\n-- Installing R"
"$PWD/install/install-R"

# Install go
echo -e "\n-- Installing go"
"$PWD/install/install-go"

# Install cht
echo -e "\n-- Installing cht.sh CLI client"
"$PWD/install/install-cht"

# Install go binaries
go install github.com/charmbracelet/mods@latest
go install github.com/stefanlogue/meteor@latest

# Python global utilities
pipx install tldr
pipx install td-watson

# Configs
for i in bash git vim tmux python;
do
  echo "Setup $i"
  cd $i && ./setup
  cd ..
done
