#!/bin/bash

# From get.docker
is_wsl() {
	case "$(uname -r)" in
	*microsoft* ) true ;; # WSL 2
	*Microsoft* ) true ;; # WSL 1
	* ) false;;
	esac
}

# Updating repository and upgrading system 
echo -e "\n-- Update and upgrade" 
sudo apt update
sudo apt upgrade  -y

echo -e "\n-- Installing various app from debian package manager"
sudo apt install vim tmux tree shellcheck podman -qq

# Install install github CLI
echo -e "\n-- Installing gh"
"$PWD/install/install-gh"

# install python
echo -e "\n-- Installing Python"
"$PWD/install/install-python"

# Install R
echo -e "\n-- Installing R"
"$PWD/install/install-R"

# ==== Only for linux workstation ====== #
if ! is_wsl
then
  # From dpkg
  echo -e "\n-- installing stuff from dpkg (workstation)"
  sudo apt install alacritty -y
  sudo apt install default-jre libreoffice-java-common -y # For libre office

  # Install from flatpak
  echo -e "\n-- Installing various app from flatpak"
  "$PWD/install/install-from-flatpak"

  # Install fonts
  echo -e "\n-- Installing fonts"
  "$PWD/install/install-fonts"

  # Manual installation
  echo -e "\n-- Done executing setup scripts"
  echo "Still need to manually install some application"
  echo "exec $PWD/install/install-web-releases to display releases in firefox"
fi

# Source all setup
echo -e "\n-- App configurations"
"$PWD/configs"
