#!/bin/bash

# Updating repository and upgrading system 
echo -e "\n-- Update and upgrade" 
sudo apt update
sudo apt upgrade  -y

echo -e "\n-- Installing various app from debian package manager"
sudo apt install vim -y
sudo apt install tmux -y
sudo apt install entr -y 
sudo apt install tree -y
sudo apt install xclip -y
sudo apt install shellcheck -y
sudo apt install fzf -y
sudo apt install ripgrep -y
sudo apt install bat -y
sudo apt install curl -y
sudo apt install age -y

# Configs
for i in bash git vim tmux ipython;
do
  echo "Setup $i"
  cd $i && ./setup
  cd ..
done

# Install stuff
cd "$PWD/install"

echo -e "\n-- Installing gh"
"$PWD/install-gh"

echo -e "\n-- Installing R"
"$PWD/install-R"

echo -e "\n-- Installing go"
"$PWD/install-go"

echo -e "\n-- Installing cht.sh CLI client"
"$PWD/install-cht"

echo -e "\n-- Installing docker"
"$PWD/install-docker"

echo -e "\n-- Installing miniconda3"
"$PWD/install-miniconda3"

cd ..

# Install go binaries
go install github.com/charmbracelet/mods@latest
go install github.com/stefanlogue/meteor@latest
go install github.com/rwxrob/keg/cmd/keg@latest

# Python global utilities
pipx install ensurepath # Change for local implementation of path
pipx install tldr
pipx install td-watson

# Link personnal scripts
echo "Symlink scripts"
ln -sf "$PWD/scripts" "$HOME/Scripts"

