#!/bin/bash

# Check all folders in ./dotfiles
# and run setup in each of them

for folder in dotfiles/*; do

  # For printing
  basename="${folder##*/}"
  
  # Check if setup file exists and run it
  if [ -f "$folder/setup" ]; then
	cd "$folder" || exit
	echo "Setup $basename"
	"./setup"
	cd - || exit
  fi
done
