#!/bin/bash
# Install vim-plug (Download plug.vim and put it in autoload directory)
if [ -f ~/.vim/autoload/plug.vim ];
then
  echo "Vim-Plug already in autoload"
else
  echo "Installing Vim-Plug"	
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Create symbolic link
echo "Creating symbolic links"
ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/colors" "$HOME/.vim/colors"
