#!/bin/bash
# VIM
## Install vim-plug (Download plug.vim and put it in autoload directory)
if [ -f ~/.vim/autoload/plug.vim ];
then
  echo "Vim-Plug already in autoload"
else
  echo "Installing Vim-Plug"	
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# NVIM
## Install vim-plug
if [ -f ~/.local/share/nvim/site/autoload/plug.vim ];
then
  echo "Nvim-Plug already in autoload"
else
  echo "Installing Nvim-Plug"
  curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Create nvim config directory
if [ -d ~/.config/nvim ];
then
  echo "nvim config directory already exists"
else
  echo "Creating nvim config directory"
  mkdir -p ~/.config/nvim
fi

# Create symbolic link
echo "Creating symbolic links"
ln -sf "$PWD/vimrc" "$HOME/.vimrc"
ln -sf "$PWD/init.vim" "$HOME/.config/nvim/init.vim"
