#!/bin/bash

## update indices
sudo apt update -qq

if  command -v "R" &> /dev/null  
then
  echo "R is already installed, trying to update"
else
  ## install two helper packages we need
  sudo apt install --no-install-recommends software-properties-common dirmngr -qq

  ## add the signing key (by Michael Rutter) for these repos
  ## To verify key, run gpg --show-keys /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc 

  ## Fingerprint: E298A3A825C0D65DFD57CBB651716619E084DAB9
  wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc

  ## add the R 4.0 repo from CRAN -- adjust 'focal' to 'groovy' or 'bionic' as needed
  sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
fi

# Install R
sudo apt install --no-install-recommends r-base -y
sudo apt install r-base-dev -y

# Install radian (if python's installed)
if command -v "pipx" &> dev/null
then
  pipx install radian --quiet
fi

# Install ipython R kernel
sudo apt install r-cran-irkernel -qq
