#!/bin/sh

echo "Download latest stable release"
wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb
echo "Install neovim"
sudo apt install ./nvim-linux64.deb
rm ./nvim-linux64.deb



