#!/bin/bash

echo -e "\n-------- Fonts -------------"

if [ ! -d $HOME/.local/share/fonts ]
then
  echo "Creating ~/.local/share/fonts"
  mkdir -p $HOME/.local/share/fonts;
fi

if [! -f $HOME/.local/share/fonts/hasklug_nf_complete.otf ]
then
   echo "Installing hasklug nerd font"
   wget -O $HOME/.local/share/fonts/hasklug_nf_complete.otf https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hasklig/Regular/complete/Hasklug%20Nerd%20Font%20Complete.otf?raw=true 
else
   echo "hasklug nerd font already installed!"
fi

if [! -f $HOME/.local/share/fonts/hasklug_nf_complete.otf ]
then
   echo "Installing hasklug nerd font mono"
   wget -O $HOME/.local/share/fonts/hasklug_nf_complete_mono.otf https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/Hasklig/Regular/complete/Hasklug%20Nerd%20Font%20Complete%20Mono.otf?raw=true 
else
   echo "hasklug nerd font mono already installed!"
fi

# Clear and restart cache
echo "Clear and restart cache"
fc-cache -f -v
