#!/bin/bash

# Tell Ubunte about the binaries at CRAN

## update indices
sudo apt update -qq

if  command -v "R" &> /dev/null  
then
  echo "R is already installed, trying to update"
else
  ## install two helper packages we need
  sudo apt install --no-install-recommends software-properties-common dirmngr -qq

  ## add the signing key (by Michael Rutter) for these repos
  ## To verify key, run gpg --show-keys /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc 

  ## Fingerprint: E298A3A825C0D65DFD57CBB651716619E084DAB9
  wget -qO- https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc | sudo tee -a /etc/apt/trusted.gpg.d/cran_ubuntu_key.asc

  ## add the R 4.0 repo from CRAN -- adjust 'focal' to 'groovy' or 'bionic' as needed
  sudo add-apt-repository "deb https://cloud.r-project.org/bin/linux/ubuntu $(lsb_release -cs)-cran40/"
fi

# Install R
sudo apt install --no-install-recommends r-base -y
sudo apt install r-base-dev -y

# Add binaries repository
sudo add-apt-repository ppa:c2d4u.team/c2d4u4.0+ -y

# Install radian (if python's installed)
if command -v "pip" &> dev/null
then
  pip install radian --quiet
fi

# Create/Change local lib path
output=$(Rscript --vanilla -e "version = R.version; print(paste('R', version\$major, version\$minor, sep='.'))")
version=$(sed 's/\[1\] \"\(.*\)\"/\1/' <(echo "$output"))
libpath="$HOME/.local/lib/$version"

if [ ! -d "$libpath" ];then
  echo "Creating $libpath"
  mkdir "$libpath"
  echo "Modify ~/.Renviron"
  echo "R_LIBS_USER=$libpath" > "$HOME/.Renviron"
fi

# install lintr
echo "Installing lintr"
Rscript --vanilla -e "install.packages('lintr', lib='$libpath', repos='https://cloud.r-project.org')"

# Install ipython R kernel
sudo apt install r-cran-irkernel -qq
