#!/bin/bash

# From web
echo "-------- Install from web --------"

## pcloud
echo "Opening browser to pcloud release"
firefox https://www.pcloud.com/download-free-online-cloud-file-storage.html

## via
echo "Opening browser to via release"
firefox https://github.com/the-via/releases/releases/

## Beekeeper-Studio
echo "Opening browser to via release"
firefox https://github.com/beekeeper-studio/beekeeper-studio/releases

## Antidote
echo "Opening browser to Antidote release"
firefox https://services.druide.com/?contexte=code_antidote&langue=en
