#!/bin/bash

# In case ~/.local/bin not in path
if [[ ! :$PATH: == *:"$HOME/.local/bin:$PATH":* ]] ; then
   export PATH="$HOME/.local/bin:$PATH"   
fi

# Install pipx 
echo "Installing pipx..." # For radian
sudo apt install pipx -y

# Install venv
echo "Installing venv..." # For radian
sudo apt install python3-venv -y

echo "Installing ipython..." # For radian
sudo apt install python3-ipython -y

echo "Installing jupyterlab..."
pipx install jupyterlab

# Create ipython config
if [ ! -d "$HOME/.ipython/profile_default" ]; then
  echo "Creating default ipython profile"
  ipython3 profile create
fi

echo "Create symbolic links for ipython config"
ln -sf "$PWD/ipython_config.py" \
  "$HOME/.ipython/profile_default/ipython_config.py"

