#!/bin/bash
# Sync TaskWarrior with Google Tasks

# Check it tw_gtasks_sync is present as a command line tool
if ! [ -x "$(command -v tw_gtasks_sync)" ]; then
    echo "tw_gtasks_sync not found. Please install it first."
    exit 1
fi

# Sync
printf "Syncing TaskWarrior with Google Tasks...\n"

printf "Syncing Backlog...\n"
tw_gtasks_sync -l "Backlog" -f "+backlog" -p "Polygon"

printf "Syncing En cours...\n"
tw_gtasks_sync -l "En cours" -f "-backlog -blocked" -p "Polygon"

printf "Syncing Bloqué...\n"
tw_gtasks_sync -l "Bloqué" -f "-backlog +blocked" -p "Polygon"

