#!/bin/bash

# Create symbolik link
echo "creating symbolik link"
ln -sf "$PWD/tmux.conf" "$HOME/.tmux.conf"

# Add autocompletion (.bash_completion is autoloaded by bash-completion)
echo "Copyin autocompletion"
cp "$PWD/tmux_completion" "$HOME/.bash_completion"
