#!/bin/bash

# Creating symbolic link
echo "create symbolic links"
#ln -sf "$PWD/bashrc_personnal" "$HOME/.bashrc_personnal"
ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/inputrc" "$HOME/.inputrc"

# Copy zscript
# Stop using it for the moment
#echo "Copying zscripts"
#cp -f "$PWD/z.sh" "$HOME/.zsh"
