#!/bin/bash

# Creating symbolic link
echo "create symbolic links"
ln -sf "$PWD/bashrc" "$HOME/.bashrc"
ln -sf "$PWD/bashrc_tools" "$HOME/.bashrc_tools"
ln -sf "$PWD/bashrc_git" "$HOME/.bashrc_git"
ln -sf "$PWD/inputrc" "$HOME/.inputrc"

# Copy zscript
# Stop using it for the moment
#echo "Copying zscripts"
#cp -f "$PWD/z.sh" "$HOME/.zsh"
